FROM python:3.6-slim
MAINTAINER Anthony Miyaguchi <amiyaguchi@mozilla.com>

ENV PYTHONUNBUFFERED=1 \
    PORT=8000

EXPOSE $PORT

WORKDIR /app
COPY . /app

RUN pip install pipenv
RUN pipenv sync

CMD ["pipenv", "run", "python", "service/app.py"]
